// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_i_am_jump_addicted = "CgkIlo304KkXEAIQDA"; // <GPGSID>
        public const string achievement_well_played = "CgkIlo304KkXEAIQBA"; // <GPGSID>
        public const string achievement_high_jump = "CgkIlo304KkXEAIQCg"; // <GPGSID>
        public const string achievement_even_more_fun = "CgkIlo304KkXEAIQBQ"; // <GPGSID>
        public const string achievement_a_little_hero = "CgkIlo304KkXEAIQBw"; // <GPGSID>
        public const string leaderboard_max_score = "CgkIlo304KkXEAIQAQ"; // <GPGSID>
        public const string achievement_thasts_for_free = "CgkIlo304KkXEAIQDg"; // <GPGSID>
        public const string achievement_a_hero = "CgkIlo304KkXEAIQCA"; // <GPGSID>
        public const string achievement_1_km_up = "CgkIlo304KkXEAIQDQ"; // <GPGSID>
        public const string achievement_i_love_jumping = "CgkIlo304KkXEAIQCw"; // <GPGSID>
        public const string achievement_that_was_easy = "CgkIlo304KkXEAIQAw"; // <GPGSID>
        public const string achievement_a_big_hero = "CgkIlo304KkXEAIQCQ"; // <GPGSID>
        public const string achievement_first_blood = "CgkIlo304KkXEAIQAg"; // <GPGSID>
        public const string achievement_im_a_little_addicted = "CgkIlo304KkXEAIQBg"; // <GPGSID>

}

